### ISSUE TITLE
What is display in file ch2_r2_visualize_bits_qubits.py?

### ISSUE THREAD

**Issue by VansFannel** [PacktPublishing/Quantum-Computing-with-IBM-Qx-Cookbook#1]
On file Quantum-Computing-in-Practice-with-Qiskit-and-IBM-Quantum-Experience/Chapter02/ch2_r2_visualize_bits_qubits.py you have the line:

`display(plot_bloch_vector(bloch, title=bit))`

But display isn't defined.

What is display?

**Comment by ordmoj** [comment]
Hi. Display is explained on page 98 in the book: Ch4 Starting at the Ground Level with Terra, Technical requirements 

> In the code examples in this book, you will sometimes see the following line of code:
> `from IPython.core.display import display`
> Depending on your environment, iPython might not display graphical output directly in the output. If this is the case, you can use the display() method to force the output, like this:
> `display(qc.draw('mpl'))`
> This example prints the quantum circuit qc to the iPython console.

And I agree that this description could have been added slightly earlier.

Hope that helps?

**Comment by VansFannel** [comment]
Hi!

Yes, it helps a lot but you need to add the import. The import is missing in file ch2_r2_visualize_bits_qubits.py.

Kind regards!

**Comment by ordmoj** [comment]
Thanks for pointing that out. Fixed!
